@startuml

top to bottom direction

class Action {
    +execute(): void
    +undo(): void
}

class ActionController {
    +doAction(action: Action): void
    +undo(): void
    +redo(): void
}

Action <|-- AddAction
Action <|-- DeleteAction
Action <|-- OtherAction

AddAction --> DeleteAction : "undo() calls"
DeleteAction --> AddAction : "undo() calls"

ActionController --> Action : "Manages"

@enduml
